### ISSUE TITLE
[Discussion] Comparison among different algorithms.

### ISSUE THREAD

**Issue by L-M-Sherlock** [nickhnsn/facharbeit-spaced-repetition#1]
Hi, Nick. I received your email, but I was not available recently. Sorry for not getting back to you sooner.

I would like to know which aspect you want to compare. The efficiency or the accuracy of algorithms?

You can learn about this code to compare the accuracy of algorithms:
https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/32575846/222408528-657dc611-8108-4ece-830a-efc2991a1bc5.png">

If you want to compare the efficiency, please see the following: https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_simulator.ipynb

**Comment by nickhnsn** [comment]
Hi Jarrett,

Thanks for your provided information! I would like to compare the efficiency of the implemented algorithms since the comparison of accuracy is too extensive in my case. I will have a look at your simulator for the FSRS algorithm as soon as I have time!

**Comment by nickhnsn** [comment]
Thank you, I used your simulator output for the comparison in my paper!
